export enum Direction {
  UP = 'UP',
  DOWN = 'DOWN',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  UP_AND_LEFT = 'UP_AND_LEFT',
  UP_AND_RIGHT = 'UP_AND_RIGHT',
  DOWN_AND_LEFT = 'DOWN_AND_LEFT',
  DOWN_AND_RIGHT = 'DOWN_AND_RIGHT',
  NO_DIRECTION = 'NO_DIRECTION',
}
