name: Node.js CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: node_modules
        path: ./node_modules
  test:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - run: npm test
    - run: npm run typecheck
    - run: npm run lint
    - run: npm run build
      env:
        CI: true
