name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Extract Branch Name
      run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Typecheck
      run: npm run typecheck
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
    - name: Publish if version has been updated
      if: env.BRANCH == 'master'
      uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
      with:
        commit_pattern: "^(\\d+\\.\\d+\\.\\d+)$"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
